ci: output a failure in the completion step if a previous step failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -261,5 +261,12 @@ jobs:
     runs-on: "ubuntu-latest"
     steps:
       - name: CI Passed
+        if: ${{ success() }}
         run: |
           echo "CI workflow completed."
+
+      - name: CI Failed
+        if: ${{ failure() }}
+        run: |
+          echo "CI workflow failed."
+          exit 1
