okay now if I add failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -265,8 +265,8 @@ jobs:
         run: |
           echo "CI workflow completed successfully.";
 
-      # - name: CI Failed
-      #   if: ${{ failure() }}
-      #   run: |
-      #     echo "CI workflow failed at some point.";
-      #     exit 1;
+      - name: CI Failed
+        if: ${{ failure() }}
+        run: |
+          echo "CI workflow failed at some point.";
+          exit 1;
